#!/usr/bin/env node
// Turn the unit JSON files into src/data/path/{a1,a2,b1,b2}.js, in syllabus order.
//   node tools/path/assemble.mjs <dir-with-unit-json> [--syllabus syllabus.json]
// Validate first (validate.mjs); this script does not check content.

import fs from 'fs';
import path from 'path';

const args = process.argv.slice(2);
const dir = args.find(a => !a.startsWith('--'));
const sylPath = args.includes('--syllabus') ? args[args.indexOf('--syllabus') + 1] : null;
if (!dir) { console.error('usage: assemble.mjs <dir> [--syllabus file]'); process.exit(2); }

const here = path.dirname(new URL(import.meta.url).pathname);
const outDir = path.resolve(here, '../../src/data/path');
const order = sylPath ? JSON.parse(fs.readFileSync(sylPath, 'utf8')).units.map(u => u.id) : null;

const units = fs.readdirSync(dir).filter(f => f.endsWith('.json')).map(f => JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')));
units.sort((a, b) => (order ? order.indexOf(a.id) - order.indexOf(b.id) : a.id.localeCompare(b.id)));

const KEYS = ['id', 'level', 'icon', 'title', 'grammar', 'explain', 'words', 'sentences', 'exercises'];
const pick = u => Object.fromEntries(KEYS.filter(k => k in u).map(k => [k, u[k]]));

for (const level of ['A1', 'A2', 'B1', 'B2']) {
  const mine = units.filter(u => u.level === level).map(pick);
  // One unit per line: compact to load, still line-diffable.
  const body = mine.length ? '[\n' + mine.map(u => '  ' + JSON.stringify(u)).join(',\n') + '\n]' : '[]';
  const src = `// ${level} units of the course path. Shape: see ./index.js.\n// Generated by tools/path/assemble.mjs from the unit files; edit those, then re-run.\nexport const ${level} = ${body};\n`;
  fs.writeFileSync(path.join(outDir, `${level.toLowerCase()}.js`), src);
  console.log(`${level}: ${mine.length} units → ${path.join(outDir, `${level.toLowerCase()}.js`)}`);
}
